# Generated by Django 6.0 on 2025-12-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
